# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFinances' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFinances

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Firebase/Core'
pod 'Firebase/Auth' 
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'Firebase/Analytics'
pod 'SnapKit', '~> 5.0.0'
pod 'InputMask'
pod 'Charts'
pod 'ProgressHUD'

end
